name: Action ci

on:
  push:
    branches: [main, develop, refactor]
  pull_request:
    branches: [main, develop, refactor]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous RedundantBuilds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependecies
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: npm run eslint
